version: '3.3'
services:
    db:
        container_name: db
        build:
            context: ./conf/
            dockerfile: docker-images/DockerfileMySQL
        volumes:
            - ./mysql-dump/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: j2ee_user
            MYSQL_PASSWORD: j2ee_password
            MYSQL_DATABASE: j2ee_project_db
        restart: always
        ports:
            - '3307:3306'
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - '8081:80'
        environment:
            PMA_HOST: db